export { SpeechProvider, useSpeechContext } from './components/speech-provider';
export { SpeechSettingsModal } from './components/speech-settings-modal';
export { SpeechSettings } from './components/speech-settings';
export { VoicesList } from './components/voices-list';
export { useSpeech } from './hooks/use-speech';
export type { UseSpeechReturn } from './hooks/use-speech';
export { useKokoroModelStatus } from './hooks/use-kokoro-model-status';
export { preloadKokoro } from './lib/providers/kokoro';
export type { KokoroModelStatus } from './lib/providers/kokoro-status';
export type { SpeechResponse, SpeechStreamHooks } from './types';
export type { VoiceSettingsFormData } from './types/schemas';
