interface Theme {
  border: string;
  bg: string;
  borderLg: string;
  bgHover: string;
  bgActive: string;
  text: string;
  textHover: string;
  ringOffset: string;
  textLight: string;
}

export const themes = {
  indigo: {
    border: "border-indigo-300",
    bg: "bg-indigo-500",
    borderLg: "border-indigo-400",
    bgHover: "hover:bg-indigo-500/75",
    bgActive: "bg-indigo-600",
    text: "text-indigo-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-indigo-600",
    textLight: "text-indigo-300",
  },
  violet: {
    border: "border-violet-300",
    bg: "bg-violet-500",
    borderLg: "border-violet-400",
    bgHover: "hover:bg-violet-500/75",
    bgActive: "bg-violet-600",
    text: "text-violet-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-violet-600",
    textLight: "text-violet-300",
  },
  purple: {
    border: "border-purple-300",
    bg: "bg-purple-500",
    borderLg: "border-purple-400",
    bgHover: "hover:bg-purple-500/75",
    bgActive: "bg-purple-600",
    text: "text-purple-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-purple-600",
    textLight: "text-purple-300",
  },
  blue: {
    border: "border-blue-300",
    bg: "bg-blue-500",
    borderLg: "border-blue-400",
    bgHover: "hover:bg-blue-500/75",
    bgActive: "bg-blue-600",
    text: "text-blue-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-blue-600",
    textLight: "text-blue-300",
  },
  cyan: {
    border: "border-cyan-300",
    bg: "bg-cyan-500",
    borderLg: "border-cyan-400",
    bgHover: "hover:bg-cyan-500/75",
    bgActive: "bg-cyan-600",
    text: "text-cyan-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-cyan-600",
    textLight: "text-cyan-300",
  },
  teal: {
    border: "border-teal-300",
    bg: "bg-teal-500",
    borderLg: "border-teal-400",
    bgHover: "hover:bg-teal-500/75",
    bgActive: "bg-teal-600",
    text: "text-teal-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-teal-600",
    textLight: "text-teal-300",
  },
  emerald: {
    border: "border-emerald-300",
    bg: "bg-emerald-500",
    borderLg: "border-emerald-400",
    bgHover: "hover:bg-emerald-500/75",
    bgActive: "bg-emerald-600",
    text: "text-emerald-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-emerald-600",
    textLight: "text-emerald-300",
  },
  green: {
    border: "border-green-300",
    bg: "bg-green-500",
    borderLg: "border-green-400",
    bgHover: "hover:bg-green-500/75",
    bgActive: "bg-green-600",
    text: "text-green-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-green-600",
    textLight: "text-green-300",
  },
  lime: {
    border: "border-lime-300",
    bg: "bg-lime-500",
    borderLg: "border-lime-400",
    bgHover: "hover:bg-lime-500/75",
    bgActive: "bg-lime-600",
    text: "text-lime-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-lime-600",
    textLight: "text-lime-300",
  },
  yellow: {
    border: "border-yellow-300",
    bg: "bg-yellow-500",
    borderLg: "border-yellow-400",
    bgHover: "hover:bg-yellow-500/75",
    bgActive: "bg-yellow-600",
    text: "text-yellow-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-yellow-600",
    textLight: "text-yellow-300",
  },
  amber: {
    border: "border-amber-300",
    bg: "bg-amber-500",
    borderLg: "border-amber-400",
    bgHover: "hover:bg-amber-500/75",
    bgActive: "bg-amber-600",
    text: "text-amber-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-amber-600",
    textLight: "text-amber-300",
  },
  orange: {
    border: "border-orange-300",
    bg: "bg-orange-500",
    borderLg: "border-orange-400",
    bgHover: "hover:bg-orange-500/75",
    bgActive: "bg-orange-600",
    text: "text-orange-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-orange-600",
    textLight: "text-orange-300",
  },
  red: {
    border: "border-red-300",
    bg: "bg-red-500",
    borderLg: "border-red-400",
    bgHover: "hover:bg-red-500/75",
    bgActive: "bg-red-600",
    text: "text-red-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-red-600",
    textLight: "text-red-300",
  },
  rose: {
    border: "border-rose-300",
    bg: "bg-rose-500",
    borderLg: "border-rose-400",
    bgHover: "hover:bg-rose-500/75",
    bgActive: "bg-rose-600",
    text: "text-rose-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-rose-600",
    textLight: "text-rose-300",
  },
  slate: {
    border: "border-slate-300",
    bg: "bg-slate-500",
    borderLg: "border-slate-400",
    bgHover: "hover:bg-slate-500/75",
    bgActive: "bg-slate-600",
    text: "text-slate-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-slate-600",
    textLight: "text-slate-300",
  },
  gray: {
    border: "border-gray-300",
    bg: "bg-gray-500",
    borderLg: "border-gray-400",
    bgHover: "hover:bg-gray-500/75",
    bgActive: "bg-gray-600",
    text: "text-gray-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-gray-600",
    textLight: "text-gray-300",
  },
  zinc: {
    border: "border-zinc-300",
    bg: "bg-zinc-500",
    borderLg: "border-zinc-400",
    bgHover: "hover:bg-zinc-500/75",
    bgActive: "bg-zinc-600",
    text: "text-zinc-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-zinc-600",
    textLight: "text-zinc-300",
  },
  stone: {
    border: "border-stone-300",
    bg: "bg-stone-500",
    borderLg: "border-stone-400",
    bgHover: "hover:bg-stone-500/75",
    bgActive: "bg-stone-600",
    text: "text-stone-200",
    textHover: "hover:text-white",
    ringOffset: "focus:ring-offset-stone-600",
    textLight: "text-stone-300",
  },
} as const;

export type ThemeColor = keyof typeof themes;
